---
nodes:
  hostname: scylladb
  count: 3
  cpu: 2
  memory: 4096
support_user: support
ip:
  network: '192.168.1.'
  node_start: 40
  domain: 'abccorp.local'
bridge: enp9s0
software:
  box: bento/ubuntu-24.04
  scylladb: 6.2